name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup tmate sessionya
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
